"""
Aggregation, statistics, and figures for the hospital language drift study.

Produces the full PROMPT.md figure set:
  figure_1_twin_timeseries.png   — per-system op vs rel rate over time, bootstrap CIs
  figure_2_ratio.png             — op/rel ratio per system, log scale
  figure_3_heatmap.png           — terms × years z-score heatmap
  figure_4_volcano.png           — per-term log2 fold-change vs significance
  figure_5_patient_collocations  — generated by collocations.py
  figure_6_baseline_ratio.png    — generated by baseline.py
  figure_7_emerged_vs_declined.png — asymmetric drift panel
  model_results.txt              — mixed-effects model summary
"""
from pathlib import Path
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.patches import Patch
from scipy import stats
from pipeline import load_corpus, OPERATIONAL_TERMS, RELATIONAL_TERMS

warnings.filterwarnings("ignore")

ROOT   = Path(__file__).parent
REPORT = ROOT / "report"
REPORT.mkdir(parents=True, exist_ok=True)

NAVY   = "#1f3d6e"; RED = "#b22222"; GOLD = "#c89d2a"
GREEN  = "#5a7b3e"; PURPLE = "#6b3d7c"
SYSTEM_COLORS = {
    "ucsf": NAVY, "stanford": RED, "michigan": GOLD,
    "duke": PURPLE, "ucdavis": GREEN,
}
SYSTEM_ORDER = ["ucsf", "stanford", "michigan", "duke", "ucdavis"]

mpl.rcParams.update({
    "font.family": "DejaVu Sans",
    "axes.spines.top": False, "axes.spines.right": False,
    "axes.titlesize": 10, "axes.labelsize": 9,
    "xtick.labelsize": 8, "ytick.labelsize": 8,
    "figure.dpi": 110, "savefig.dpi": 150, "savefig.bbox": "tight",
})

# ---------------------------------------------------------------------------
# Load corpus
# ---------------------------------------------------------------------------
df = load_corpus()
df["period"] = np.where(df["year"] <= 2016, "early (2010-2016)", "late (2017-2025)")
print(f"Corpus: {len(df)} documents")
print(df.groupby(["system", "period", "doctype"]).size().unstack(fill_value=0))

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def weighted_rate(g, count_col, token_col):
    return 10000 * g[count_col].sum() / max(g[token_col].sum(), 1)

def bootstrap_ci(values, n_boot=1000, ci=0.95):
    if len(values) == 0:
        return np.nan, np.nan
    boots = np.random.choice(values, size=(n_boot, len(values)), replace=True).mean(axis=1)
    lo = np.percentile(boots, (1 - ci) / 2 * 100)
    hi = np.percentile(boots, (1 + ci) / 2 * 100)
    return lo, hi

# Per-document tables
summary = df[["system","year","doctype","n_tokens","op_total","rel_total",
              "op_rate_per_10k","rel_rate_per_10k"]].copy()
summary["ratio_op_to_rel"] = (summary["op_rate_per_10k"]
                               / summary["rel_rate_per_10k"].replace(0, np.nan))
summary.to_csv(REPORT / "summary_per_doc.csv", index=False)

# Cell aggregates
cells, pr_cells = [], []
for (sys, period), g in df.groupby(["system","period"]):
    row = {"system":sys,"period":period,"n_docs":len(g),
           "n_tokens":g["n_tokens"].sum(),
           "op_rate": weighted_rate(g,"op_total","n_tokens"),
           "rel_rate":weighted_rate(g,"rel_total","n_tokens")}
    row["ratio_op_to_rel"] = row["op_rate"] / max(row["rel_rate"], 1e-9)
    cells.append(row)
    if (g["doctype"] == "press_release").all() or True:
        pr_cells.append(row)

cells_df    = pd.DataFrame(cells)
pr_cells_df = pd.DataFrame(pr_cells)
cells_df.to_csv(REPORT / "summary_by_cell.csv", index=False)
print("\n=== Cell summary ===")
print(cells_df.to_string(index=False))

# Press-release only
pr_only = df[df["doctype"] == "press_release"].copy()
pr_cell_rows = []
for (sys, period), g in pr_only.groupby(["system","period"]):
    row = {"system":sys,"period":period,"n_docs":len(g),
           "n_tokens":g["n_tokens"].sum(),
           "op_rate": weighted_rate(g,"op_total","n_tokens"),
           "rel_rate":weighted_rate(g,"rel_total","n_tokens")}
    row["ratio_op_to_rel"] = row["op_rate"] / max(row["rel_rate"], 1e-9)
    pr_cell_rows.append(row)
pr_cells_df = pd.DataFrame(pr_cell_rows)
pr_cells_df.to_csv(REPORT / "summary_press_releases_only.csv", index=False)
print("\n=== Press-releases only ===")
print(pr_cells_df.to_string(index=False))

# Term-level long tables
def term_counts_df(docs, kind):
    rows = []
    col = "op_counts" if kind == "op" else "rel_counts"
    for _, d in docs.iterrows():
        for term, c in d[col].items():
            rows.append({"system":d["system"],"year":d["year"],"period":d["period"],
                         "doctype":d["doctype"],"term":term,"count":c,
                         "n_tokens":d["n_tokens"]})
    return pd.DataFrame(rows)

op_long  = term_counts_df(df, "op");  op_long["category"]  = "operational"
rel_long = term_counts_df(df, "rel"); rel_long["category"] = "relational"
both     = pd.concat([op_long, rel_long], ignore_index=True)

term_period = both.groupby(["category","term","period"]).agg(
    count=("count","sum"), tokens=("n_tokens","sum")).reset_index()
term_period["rate_per_10k"] = 10000 * term_period["count"] / term_period["tokens"].clip(1)
term_period.to_csv(REPORT / "term_rates_by_period.csv", index=False)

tp_pivot = term_period.pivot_table(
    index=["category","term"], columns="period",
    values="rate_per_10k", fill_value=0).reset_index()
tp_pivot.columns.name = None
tp_pivot = tp_pivot.rename(columns={"early (2010-2016)":"early","late (2017-2025)":"late"})
tp_pivot["delta"]   = tp_pivot["late"]  - tp_pivot["early"]
tp_pivot["log2fc"]  = np.log2((tp_pivot["late"] + 1) / (tp_pivot["early"] + 1))
tp_pivot.to_csv(REPORT / "term_fold_changes.csv", index=False)

# ---------------------------------------------------------------------------
# FIGURE 1: Twin time-series — 5-panel small multiples with bootstrap CIs
# ---------------------------------------------------------------------------
systems_present = [s for s in SYSTEM_ORDER if s in df["system"].unique()]
fig, axes = plt.subplots(1, len(systems_present), figsize=(3.2 * len(systems_present), 4.5),
                         sharey=False)
if len(systems_present) == 1:
    axes = [axes]

for ax, sys in zip(axes, systems_present):
    sub = df[df["system"] == sys]
    years = sorted(sub["year"].unique())
    op_means, op_lo, op_hi = [], [], []
    rel_means, rel_lo, rel_hi = [], [], []
    for yr in years:
        g = sub[sub["year"] == yr]
        op_v  = g["op_rate_per_10k"].values
        rel_v = g["rel_rate_per_10k"].values
        op_means.append(np.mean(op_v))
        rel_means.append(np.mean(rel_v))
        lo, hi = bootstrap_ci(op_v);  op_lo.append(lo);  op_hi.append(hi)
        lo, hi = bootstrap_ci(rel_v); rel_lo.append(lo); rel_hi.append(hi)

    years = np.array(years)
    op_means  = np.array(op_means)
    rel_means = np.array(rel_means)

    ax.fill_between(years, op_lo,  op_hi,  alpha=0.15, color=RED)
    ax.fill_between(years, rel_lo, rel_hi, alpha=0.15, color=NAVY)
    ax.plot(years, op_means,  color=RED,  linewidth=1.8, marker="o", ms=4, label="operational")
    ax.plot(years, rel_means, color=NAVY, linewidth=1.8, marker="s", ms=4, label="relational")
    ax.set_title(sys.upper(), fontweight="bold")
    ax.set_xlabel("Year")
    if ax == axes[0]:
        ax.set_ylabel("Rate per 10,000 tokens")
    ax.grid(axis="y", linestyle=":", alpha=0.3)
    ax.set_xticks([years[0], years[len(years)//2], years[-1]])

handles = [plt.Line2D([0],[0], color=RED,  lw=2, label="operational"),
           plt.Line2D([0],[0], color=NAVY, lw=2, label="relational")]
fig.legend(handles=handles, loc="lower center", ncol=2, frameon=False,
           fontsize=9, bbox_to_anchor=(0.5, -0.04))
fig.suptitle("Operational vs relational term density over time\n"
             "(press releases, bootstrap 95% CIs)", y=1.01)
plt.tight_layout()
plt.savefig(REPORT / "figure_1_twin_timeseries.png")
plt.close()
print("Saved figure_1_twin_timeseries.png")

# ---------------------------------------------------------------------------
# FIGURE 2: op/rel ratio per system, log scale
# ---------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(8, 4.5))
ratio_df = df.copy()
ratio_df["ratio"] = ratio_df["op_rate_per_10k"] / ratio_df["rel_rate_per_10k"].replace(0, np.nan)
bar_systems = [s for s in SYSTEM_ORDER if s in ratio_df["system"].unique()]
bar_periods  = ["early (2010-2016)", "late (2017-2025)"]
n = len(bar_systems)
positions = {}
for i, s in enumerate(bar_systems):
    positions[(bar_periods[0], s)] = i
    positions[(bar_periods[1], s)] = n + 1 + i

for (period, sys), pos in positions.items():
    sub = ratio_df[(ratio_df["period"] == period) & (ratio_df["system"] == sys)]
    vals  = sub["ratio"].dropna().values
    zeros = int((sub["ratio"].fillna(0) == 0).sum())
    color = SYSTEM_COLORS.get(sys, "gray")
    if len(vals):
        ax.scatter([pos] * len(vals), vals, s=55, color=color,
                   edgecolor="black", linewidth=0.5, alpha=0.8)
    if zeros:
        ax.scatter([pos] * zeros, [0.005] * zeros, s=55, marker="v",
                   color=color, edgecolor="black", linewidth=0.5, alpha=0.5)

tick_pos  = list(positions.values())
tick_labs = [f"{sys.upper()}" for (_, sys) in positions.keys()]
ax.set_xticks(tick_pos)
ax.set_xticklabels(tick_labs, rotation=30, ha="right", fontsize=8)
ax.set_yscale("symlog", linthresh=0.01)
ax.set_ylabel("Operational / relational rate (log scale)")
ax.set_title("Per-document operational-to-relational ratio by system and period")
ax.axhline(1.0, color="gray", linestyle=":", linewidth=0.8)
ax.axvline(n + 0.5, color="black", linewidth=0.4)
mid_e = (n - 1) / 2
mid_l = n + 1 + (n - 1) / 2
ybot  = ax.get_ylim()[0]
ax.text(mid_e, 0.3, "early", ha="center", fontsize=8, color="dimgray")
ax.text(mid_l, 0.3, "late",  ha="center", fontsize=8, color="dimgray")
ax.text(0.98, 0.02, "▽ = zero operational terms",
        transform=ax.transAxes, ha="right", va="bottom", fontsize=7, color="dimgray")
ax.grid(axis="y", linestyle=":", alpha=0.3)
plt.tight_layout()
plt.savefig(REPORT / "figure_2_ratio.png")
plt.close()
print("Saved figure_2_ratio.png")

# ---------------------------------------------------------------------------
# FIGURE 3: Heatmap — terms × year-buckets, z-score within term
# ---------------------------------------------------------------------------
year_buckets = [
    ("2010-2013", (2010, 2013)), ("2014-2016", (2014, 2016)),
    ("2017-2019", (2017, 2019)), ("2020-2022", (2020, 2022)),
    ("2023-2025", (2023, 2025)),
]

def bucket_rate(term_name, kind, lo, hi):
    sub = both[(both["term"] == term_name) &
               (both["category"] == kind) &
               (both["year"] >= lo) & (both["year"] <= hi)]
    if sub.empty or sub["n_tokens"].sum() == 0:
        return 0.0
    return 10000 * sub["count"].sum() / sub["n_tokens"].sum()

all_terms_sorted = (
    [("operational", t) for t in sorted(OPERATIONAL_TERMS.keys())] +
    [("relational",  t) for t in sorted(RELATIONAL_TERMS.keys())]
)

matrix = np.zeros((len(all_terms_sorted), len(year_buckets)))
for i, (cat, term) in enumerate(all_terms_sorted):
    for j, (_, (lo, hi)) in enumerate(year_buckets):
        matrix[i, j] = bucket_rate(term, cat, lo, hi)

# Z-score within each term (row), ignore all-zero rows
with np.errstate(invalid="ignore", divide="ignore"):
    row_std = matrix.std(axis=1, keepdims=True)
    row_std[row_std == 0] = 1
    z = (matrix - matrix.mean(axis=1, keepdims=True)) / row_std
z = np.nan_to_num(z, nan=0)

term_labels = [f"{'[OP] ' if cat == 'operational' else '[REL] '}{t}"
               for cat, t in all_terms_sorted]
bucket_labels = [b[0] for b in year_buckets]

fig, ax = plt.subplots(figsize=(8, 12))
im = ax.imshow(z, aspect="auto", cmap="RdBu_r", vmin=-2, vmax=2)
ax.set_xticks(range(len(bucket_labels)))
ax.set_xticklabels(bucket_labels, rotation=30, ha="right")
ax.set_yticks(range(len(term_labels)))
ax.set_yticklabels(term_labels, fontsize=7)
plt.colorbar(im, ax=ax, label="Z-score within term", shrink=0.6)
# Draw separator between op and rel sections
n_op = sum(1 for cat, _ in all_terms_sorted if cat == "operational")
ax.axhline(n_op - 0.5, color="black", linewidth=1.2)
ax.text(-0.5, n_op / 2 - 0.5, "OPERATIONAL", va="center", ha="right",
        fontsize=7, rotation=90, color=RED)
ax.text(-0.5, n_op + (len(all_terms_sorted) - n_op) / 2 - 0.5,
        "RELATIONAL", va="center", ha="right", fontsize=7, rotation=90, color=NAVY)
ax.set_title("Term frequency z-scores by time period\n(red = above average, blue = below)", pad=12)
plt.tight_layout()
plt.savefig(REPORT / "figure_3_heatmap.png")
plt.close()
print("Saved figure_3_heatmap.png")

# ---------------------------------------------------------------------------
# FIGURE 4: Volcano — log2 fold-change vs bootstrap significance
# ---------------------------------------------------------------------------
# Compute per-term Mann-Whitney p-value (early vs late doc-level rates)
pvals = []
for _, row in tp_pivot.iterrows():
    term = row["term"]; cat = row["category"]
    early_vals = both[(both["term"] == term) & (both["category"] == cat) &
                      (both["period"] == "early (2010-2016)")]["count"].values.astype(float)
    late_vals  = both[(both["term"] == term) & (both["category"] == cat) &
                      (both["period"] == "late (2017-2025)")]["count"].values.astype(float)
    if len(early_vals) >= 3 and len(late_vals) >= 3:
        _, p = stats.mannwhitneyu(early_vals, late_vals, alternative="two-sided")
    else:
        p = 1.0
    pvals.append(p)

tp_pivot["pval"] = pvals
tp_pivot["neg_log10_p"] = -np.log10(np.clip(tp_pivot["pval"], 1e-10, 1))
tp_pivot.to_csv(REPORT / "term_fold_changes.csv", index=False)

fig, ax = plt.subplots(figsize=(8.5, 6))
for _, row in tp_pivot.iterrows():
    color = RED if row["category"] == "operational" else NAVY
    sig   = row["neg_log10_p"] > -np.log10(0.05)
    ax.scatter(row["log2fc"], row["neg_log10_p"],
               color=color, s=60, alpha=0.8,
               edgecolor="black" if sig else "none", linewidth=0.6, zorder=3)
    if sig and (abs(row["log2fc"]) > 0.5 or row["neg_log10_p"] > 2):
        ax.annotate(row["term"], (row["log2fc"], row["neg_log10_p"]),
                    textcoords="offset points", xytext=(4, 2), fontsize=6.5)

ax.axhline(-np.log10(0.05), color="gray", linestyle="--", linewidth=0.8,
           label="p = 0.05")
ax.axvline(0, color="black", linewidth=0.5)
ax.set_xlabel("Log₂ fold-change (late / early)")
ax.set_ylabel("−log₁₀(p)  [Mann-Whitney, two-sided]")
ax.set_title("Per-term drift: late period vs early period\n"
             "(outlined points = p < 0.05)")
ax.legend(handles=[
    Patch(facecolor=RED,  label="operational"),
    Patch(facecolor=NAVY, label="relational"),
    plt.Line2D([0],[0], color="gray", ls="--", lw=1, label="p = 0.05"),
], loc="upper left", frameon=False, fontsize=8)
ax.grid(linestyle=":", alpha=0.25)
plt.tight_layout()
plt.savefig(REPORT / "figure_4_volcano.png")
plt.close()
print("Saved figure_4_volcano.png")

# ---------------------------------------------------------------------------
# FIGURE 7: Emerged vs declined — asymmetric drift panel
# ---------------------------------------------------------------------------
emerged  = tp_pivot[(tp_pivot["early"] == 0) & (tp_pivot["late"] > 0)].copy()
declined = tp_pivot[(tp_pivot["late"]  == 0) & (tp_pivot["early"] > 0)].copy()
changed  = tp_pivot[(tp_pivot["early"] > 0)  & (tp_pivot["late"] > 0)  &
                    (abs(tp_pivot["log2fc"]) > 0.5)].copy()

fig, axes = plt.subplots(1, 3, figsize=(13, 5))

# Panel A: Emerged (absent early, present late)
ax = axes[0]
if len(emerged):
    emerged_s = emerged.sort_values("late", ascending=True)
    colors_e  = [RED if c == "operational" else NAVY
                 for c in emerged_s["category"]]
    ax.barh(emerged_s["term"], emerged_s["late"],
            color=colors_e, edgecolor="black", linewidth=0.4)
ax.set_title("Emerged\n(0 in early, >0 in late)", fontsize=9)
ax.set_xlabel("Late-period rate / 10k")
ax.grid(axis="x", linestyle=":", alpha=0.3)

# Panel B: Declined (present early, absent late)
ax = axes[1]
if len(declined):
    declined_s = declined.sort_values("early", ascending=True)
    colors_d   = [RED if c == "operational" else NAVY
                  for c in declined_s["category"]]
    ax.barh(declined_s["term"], declined_s["early"],
            color=colors_d, edgecolor="black", linewidth=0.4)
ax.set_title("Declined\n(>0 in early, 0 in late)", fontsize=9)
ax.set_xlabel("Early-period rate / 10k")
ax.grid(axis="x", linestyle=":", alpha=0.3)

# Panel C: Changed substantially (log2fc > 0.5)
ax = axes[2]
if len(changed):
    changed_s = changed.sort_values("log2fc")
    colors_c  = [RED if c == "operational" else NAVY
                 for c in changed_s["category"]]
    ax.barh(changed_s["term"], changed_s["log2fc"],
            color=colors_c, edgecolor="black", linewidth=0.4)
ax.axvline(0, color="black", linewidth=0.5)
ax.set_title("Substantially changed\n(|log₂FC| > 0.5)", fontsize=9)
ax.set_xlabel("Log₂ fold-change (late/early)")
ax.grid(axis="x", linestyle=":", alpha=0.3)

for ax in axes:
    ax.legend(handles=[Patch(facecolor=RED,  label="operational"),
                       Patch(facecolor=NAVY, label="relational")],
              loc="lower right", frameon=False, fontsize=7)

fig.suptitle("Asymmetric vocabulary drift: emerged, declined, and changed terms", y=1.01)
plt.tight_layout()
plt.savefig(REPORT / "figure_7_emerged_vs_declined.png")
plt.close()
print("Saved figure_7_emerged_vs_declined.png")

# ---------------------------------------------------------------------------
# Mixed-effects model (statsmodels)
# ---------------------------------------------------------------------------
try:
    import statsmodels.formula.api as smf

    # Prepare: one row per doc with binary category indicator
    long_rows = []
    for _, d in df.iterrows():
        for category, rate_col in [("operational","op_rate_per_10k"),
                                   ("relational","rel_rate_per_10k")]:
            long_rows.append({
                "rate":     d[rate_col],
                "year":     d["year"] - 2010,   # centre at 2010
                "category": 1 if category == "operational" else 0,
                "system":   d["system"],
                "doctype":  d["doctype"],
            })
    ldf = pd.DataFrame(long_rows)
    ldf = ldf.dropna(subset=["rate"])

    model = smf.mixedlm(
        "rate ~ year * category",
        ldf,
        groups=ldf["system"],
    )
    result = model.fit(reml=True)
    summary_text = str(result.summary())
    (REPORT / "model_results.txt").write_text(summary_text)
    print("\nMixed-effects model fitted. Key coefficients:")
    print(result.summary().tables[1])
except Exception as exc:
    print(f"Mixed-effects model failed: {exc}")
    (REPORT / "model_results.txt").write_text(f"Model failed: {exc}\n")

# ---------------------------------------------------------------------------
# Statistical tests
# ---------------------------------------------------------------------------
pr_early = pr_only[pr_only["period"] == "early (2010-2016)"]["op_rate_per_10k"].values
pr_late  = pr_only[pr_only["period"] == "late (2017-2025)"]["op_rate_per_10k"].values
print("\n=== Press release op-rate test (early vs late) ===")
if len(pr_early) >= 3 and len(pr_late) >= 3:
    print(f"Early n={len(pr_early)}, mean={pr_early.mean():.1f}, median={np.median(pr_early):.1f}")
    print(f"Late  n={len(pr_late)},  mean={pr_late.mean():.1f}, median={np.median(pr_late):.1f}")
    u, p = stats.mannwhitneyu(pr_early, pr_late, alternative="less")
    print(f"Mann-Whitney (H₁: late > early): U={u:.0f}, p={p:.4f}")
else:
    print("Insufficient data")

pr_early_r = pr_only[pr_only["period"] == "early (2010-2016)"]["rel_rate_per_10k"].values
pr_late_r  = pr_only[pr_only["period"] == "late (2017-2025)"]["rel_rate_per_10k"].values
print("\n=== Press release rel-rate test (early vs late) ===")
if len(pr_early_r) >= 3 and len(pr_late_r) >= 3:
    print(f"Early n={len(pr_early_r)}, mean={pr_early_r.mean():.1f}, median={np.median(pr_early_r):.1f}")
    print(f"Late  n={len(pr_late_r)},  mean={pr_late_r.mean():.1f}, median={np.median(pr_late_r):.1f}")
    u, p = stats.mannwhitneyu(pr_early_r, pr_late_r, alternative="greater")
    print(f"Mann-Whitney (H₁: early > late): U={u:.0f}, p={p:.4f}")
else:
    print("Insufficient data")

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
print(f"\nAll outputs in {REPORT}")
for f in sorted(REPORT.glob("figure_*.png")):
    print(f"  {f.name}")
for f in sorted(REPORT.glob("*.csv")) + sorted(REPORT.glob("*.txt")):
    print(f"  {f.name}")
